# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amediatech/x96x9/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amediatech/x96x9

PRODUCT_COPY_FILES += \
    vendor/amediatech/x96x9/proprietary/vendor/etc/bluetooth/BCM4345C5.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/BCM4345C5.hcd \
    vendor/amediatech/x96x9/proprietary/vendor/etc/bluetooth/bt_vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor.conf \
    vendor/amediatech/x96x9/proprietary/vendor/etc/wifi/6256/fw_bcm43456c5_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6256/fw_bcm43456c5_ag.bin \
    vendor/amediatech/x96x9/proprietary/vendor/etc/wifi/6256/fw_bcm43456c5_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6256/fw_bcm43456c5_ag_apsta.bin \
    vendor/amediatech/x96x9/proprietary/vendor/etc/wifi/6256/nvram_ap6256.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6256/nvram_ap6256.txt \
    vendor/amediatech/x96x9/proprietary/vendor/etc/wifi/6256/config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6256/config.txt \
    vendor/xibo/quicksilver/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/amediatech/x96x9/proprietary/vendor/etc/tvconfig/pq/pq.db:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq.db \
    vendor/amediatech/x96x9/proprietary/vendor/etc/tvconfig/pq/pq_default.ini:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq_default.ini \
    vendor/amediatech/x96x9/proprietary/vendor/usr/idc/Vendor_1d5a_Product_c082.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_1d5a_Product_c082.idc \
    vendor/amediatech/x96x9/proprietary/vendor/usr/keylayout/Vendor_1d5a_Product_c082.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_1d5a_Product_c082.kl
    
## gdc fw
PRODUCT_COPY_FILES += \
    vendor/amediatech/x96x9/proprietary/vendor/lib/firmware/gdc/affine-1920_1080_180_1080_0_0-0_0_1080_1920-0_0_1.0-90-nv12.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/gdc/affine-1920_1080_180_1080_0_0-0_0_1080_1920-0_0_1.0-90-nv12.bin \
    vendor/amediatech/x96x9/proprietary/vendor/lib/firmware/gdc/affine-1920_1080_180_1080_0_0-0_0_1080_1920-0_0_1.0-270-nv12.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/gdc/affine-1920_1080_180_1080_0_0-0_0_1080_1920-0_0_1.0-270-nv12.bin \
    vendor/amediatech/x96x9/proprietary/vendor/lib/firmware/gdc/affine-1920_1080_180_1080_0_0-0_0_1920_1080-0_0_1.0-180-nv12.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/gdc/affine-1920_1080_180_1080_0_0-0_0_1920_1080-0_0_1.0-180-nv12.bin \
    vendor/amediatech/x96x9/proprietary/vendor/lib/firmware/gdc/affine-3840_2160_180_2160_0_0-0_0_2160_3840-0_0_1.0-90-nv12.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/gdc/affine-3840_2160_180_2160_0_0-0_0_2160_3840-0_0_1.0-90-nv12.bin \
    vendor/amediatech/x96x9/proprietary/vendor/lib/firmware/gdc/affine-3840_2160_180_2160_0_0-0_0_2160_3840_0_0_1.0-270-nv12.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/gdc/affine-3840_2160_180_2160_0_0-0_0_2160_3840_0_0_1.0-270-nv12.bin \
    vendor/amediatech/x96x9/proprietary/vendor/lib/firmware/gdc/affine-3840_2160_180_2160_0_0-0_0_3840_2160-0_0_1.0-180-nv12.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/gdc/affine-3840_2160_180_2160_0_0-0_0_3840_2160-0_0_1.0-180-nv12.bin
